apiVersion: v1
kind: Namespace
metadata:
  name: service-alexmt-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-alexmt-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-alexmt-prod
