---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edgaras@apsega.lt
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-edgaras@apsega.lt-*'
      server: http://cluster-argocon:8001
  roles:
    - name: admin
      policies:
        - p, proj:edgaras@apsega.lt:admin, *, *, edgaras@apsega.lt/*, allow
      groups:
        - edgaras@apsega.lt # please copy it from https://argocon.cd.akuity.cloud/user-info
